---
services:
  connect:
    volumes:
      - ${AWS_CREDENTIALS_FILE_NAME:-/dev/null}:$CONNECT_CONTAINER_HOME_DIR/.aws/credentials 
      - $HOME/.aws/config:$CONNECT_CONTAINER_HOME_DIR/.aws/config
      - ../../connect/connect-aws-sqs-source/$COMPONENT_NAME/target/awscredentialsprovider-1.0.0-jar-with-dependencies.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-sqs/lib/awscredentialsprovider-1.0.0-jar-with-dependencies.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-sqs
      AWS_REGION: $AWS_REGION